export enum ErrorCodes {
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	INVALID_VALUE = 'INVALID_VALUE',

	INVALID_FORMAT = 'INVALID_FORMAT',

	VALUE_REQUIRED = 'VALUE_REQUIRED',

	UNKNOWN_COMMAND = 'UNKNOWN_COMMAND',

	USER_NOT_IN_GROUP = 'USER_NOT_IN_GROUP',
}
